### PR TITLE
Check in the Kubeflow config for the latest cluster.

### PR DESCRIPTION
**Pull request by jlewi**
* Check in the Kubeflow configuration files for the cluster we are using.

Related to #70 - ensemble predictions.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/92)

### CODE REVIEW

**Comment by jlewi** [comment]
@hamelsmu can you rubberstamp this? I don't think you actually need to review the 417 files. It is all autogenerated by kfctl.

**Comment by hamelsmu** [comment]
@jlewi the bot doesn't want to merge this PR something about an owner

**Comment by jlewi** [comment]
@hamelsmu thanks I removed the offending OWNERs file.

**Pull request merged**
