### PR TITLE
Store model artifacts while training models

### PR DESCRIPTION
**Pull request by abcdefgs0324**
Use kubeflow metadata to store model artifacts while we train models.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/42)

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve
/hold

@zhenghuiwang Could you take a quick look as well please?

**Comment by abcdefgs0324** [comment]
@zhenghuiwang Fixed the merge conflict.

**Pull request merged**
