### PR TITLE
Add worker class to address events in pubsub

### PR DESCRIPTION
**Pull request by abcdefgs0324**
Design worker class
- allow mlpwrapper to load classifier from file
- add github util and app class
- add worker class to address pubsub event and do label prediction
- use fire to create entry point for worker
- update requirements.txt
- update embeddings to return issues even though they haven't been labeled

/assign @jlewi @zhenghuiwang @hamelsmu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/41)

### CODE REVIEW

**Comment by abcdefgs0324** [comment]
@jlewi The existing flask app is in [machine-learning-apps/Issue-Label-Bot](https://github.com/machine-learning-apps/Issue-Label-Bot).
I will handle your comments tomorrow.

**Comment by abcdefgs0324** [comment]
@jlewi @zhenghuiwang I fixed your comments and added some unit tests. PTAL.

**Comment by jlewi** [comment]
/lgtm
/approve
/hold
So @zhenghuiwang can finish his review.

**Pull request merged**
