### PR TITLE
Clean up notebooks and rebuild fairing images.

### PR DESCRIPTION
**Pull request by abcdefgs0324**
- Change the default values instead of the original basic settings, such as default size for hidden layers, learning rate strategy and max iteration, for classifiers. The original basic setting is too hard to have a look at the initial results because they are too "basic". They are still able to be specified in the pipeline if someone likes.
- Update the repo configs in two notebooks, which was the changes from #43.
- Clean up the notebooks to make them use the latest `/py`.
- Rebuild the fairing image for the training pipeline.

/assign @jlewi 
/assign @zhenghuiwang 
/assign @hamelsmu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/54)

### CODE REVIEW

**Comment by abcdefgs0324** [comment]
@jlewi I revised the PR description, PTAL.

**Comment by zhenghuiwang** [comment]
/lgtm

Do the new default parameters yield models with better precision and recall?

**Comment by hamelsmu** [comment]
> Do the new default parameters yield models with better precision and recall?


This is the same question (and a good question) I see every on PR concerning ML.  This is why we need CI/CD for ML so the information gets dropped automatically into the PR re: model performance.  I'm working on [this now](https://github.com/marketplace/actions/submit-argo-workflows-to-gke) but im at a really early stage.   cc: @jlewi

**Pull request merged**
