### PR TITLE
Reorganize modules under code_intelligence.

### PR DESCRIPTION
**Pull request by jlewi**
* Move the notifications module under code_intelligence.
* We want subdirectories of py to be top level modules
* This makes code reuse easier.

* Remove mark_read from triage; it is in notifications.py

* Filter out mentions on PR; assigning PRs creates lots of noisy notifications

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/23)

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jlewi Look at the README and modify it per these changes if you feel that is appropriate 

/lgtm

**Comment by jlewi** [comment]
Thanks @hamelsmu 
Updated the README PTAL

**Pull request merged**
