### PR TITLE
Compute embeddings for all kubeflow repositories.

### PR DESCRIPTION
**Pull request by jlewi**
Compute embeddings for all kubeflow repositories.

* This is the first step in creating an org wide model for all of Kubeflow (#110)

* Modify the Get-GitHub-Issues.ipynb model to reuse code in the embeddings directory.
  * Add some missing packages to requirements.txt.
  * Use the GitHub graphql client to get a list of all repositories.

* Add some missing GCS utilities

* Remove some of the duplication between Get-GitHub-Issues.ipynb and our
  library methods (#122)

* Start fetching the data from bigquery.

  * Using BigQuery turned out to be a lot better for bulk pulling all
    of the Kubeflow issues.

* Use hdf5 to save the data.

* Start a doc to keep track of notes for how to train a Kubeflow model. Add logic to save to hDF5 and do 
a sanity check compared to the inference code

* Add a function to fetch the data using the GitHub API
  * related to https://github.com/kubeflow/code-intelligence/issues/126 swiching the embeddings service t
o use the GraphQL API rather than html fetching
  * I added this function as a way to sanity check that we get the same data
    using bigquery as at inference time.

### CODE REVIEW

**Comment by jlewi** [comment]
@hamelsmu I updated the notebook Get-GitHub-Issues.ipynb
https://app.reviewnb.com/kubeflow/code-intelligence/pull/124/files/

To loop over all Kubeflow repositories and compute the embeddings.

When I did this I got the following exception.

```
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/git_kubeflow-code-intelligence/py/code_intelligence/embeddings.py in get_all_issue_text(owner, repo, inf_wrapper, workers)
    107         issues_dict['body'].append(issue['body'])
    108 
--> 109     features = inf_wrapper.df_to_embedding(pd.DataFrame.from_dict(issues_dict))
    110 
    111     assert len(features) == len(labels), 'Error you have mismatch b/w number of observations and labels.'

~/git_kubeflow-code-intelligence/py/code_intelligence/inference.py in df_to_embedding(self, dataframe, bs)
    179                                text_cols='text',
    180                                tokenizer=self.model_tokenizer,
--> 181                                vocab=self.vocab)
    182 
    183         # extract numericalized arrays and convert to pytorch

~/.local/lib/python3.6/site-packages/fastai/text/data.py in from_df(cls, path, train_df, valid_df, test_df, tokenizer, vocab, classes, text_cols, label_cols, label_delim, chunksize, max_vocab, min_freq, mark_fields, include_bos, include_eos, **kwargs)
    198         if classes is None and is_listy(label_cols) and len(label_cols) > 1: classes = label_cols
    199         src = ItemLists(path, TextList.from_df(train_df, path, cols=text_cols, processor=processor),
--> 200                         TextList.from_df(valid_df, path, cols=text_cols, processor=processor))
    201         if cls==TextLMDataBunch: src = src.label_for_lm()
    202         else:

~/.local/lib/python3.6/site-packages/fastai/data_block.py in __init__(self, path, train, valid)
    448     def __init__(self, path:PathOrStr, train:ItemList, valid:ItemList):
    449         self.path,self.train,self.valid,self.test = Path(path),train,valid,None
--> 450         if not self.train.ignore_empty and len(self.train.items) == 0:
    451             warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
    452         if not self.valid.ignore_empty and len(self.valid.items) == 0:

TypeError: len() of unsized object
```

For this repo https://github.com/kubeflow/caffe2-operator/issues/1

The think that gives me pause is the mention about training set

```
--> 450         if not self.train.ignore_empty and len(self.train.items) == 0:
    451             warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
```

Is the code not computing embeddings for each repository in a consistent way? i.e are we doing some sort of training phase for each repository that will be problematic when training an org wide model that will be used across repositories?

This is the code being invoked for each repository.
https://github.com/kubeflow/code-intelligence/blob/9bbdce34fc0d81bfb9a63493941763771d2a0746/py/code_intelligence/inference.py#L138

**Comment by jlewi** [comment]
Status:

I'm hitting some weird flakiness issues fetching the issues. I seem to be getting different numbers of issues subsequent tries for a given repo. I think we need to refactor the code so we can fetch all the issues and then compute embeddings all at once. I also want to switch to either using

* BigQuery to fetch the data
* Using the GitHub GraphQL API

**Comment by hamelsmu** [comment]
@jlewi the embedding size is definitely the same for each repo so the shapes are consistent (the first dimension will be equal to the number of rows being scored, but the second dimension will be the same).  The error appears like an empty tensor is being passed into the model ... somehow, I can take a more detailed look tomorrow to try to debug

**Comment by hamelsmu** [comment]
BTW just tried running the notebook, encountered my first issue

```
3)
ERROR: Could not find a version that satisfies the requirement fastai==1.0.53.post3 (from -r ../requirements.txt (line 22)) (from versions: 0.6, 0.7.0)
ERROR: No matching distribution found for fastai==1.0.53.post3 (from -r ../requirements.txt (line 22))
```

@jlewi did you not encounter this problem?

**Comment by jlewi** [comment]
Thanks @hamelsmu; I can figure out the empty tensor issue (I suspect its related to the scraping returning variable results on different runs). I was mostly just worried that there was a correctness issue. In particular, I was worried that each to the embeddings function was computing normalization parameters (or similar) and thus each batch of results was getting different normalization.

I didn't hit the fastai version problem. I'm using the following docker images

```
gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-cpu:1.0.0
gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0
```

Here's the output of pip freeze
[pip_freeze.txt](https://github.com/kubeflow/code-intelligence/files/4448069/pip_freeze.txt)

**Comment by jlewi** [comment]
Actually looks like i do see the error

```
ERROR: torchvision 0.5.0 has requirement torch==1.4.0, but you'll have torch 1.1.0 which is incompatible.
ERROR: kubeflow-fairing 0.7.0.1 has requirement numpy>=1.17.3, but you'll have numpy 1.16.4 which is incompatible.
ERROR: kubeflow-fairing 0.7.0.1 has requirement urllib3==1.24.2, but you'll have urllib3 1.24.3 which is incompatible.
ERROR: kfserving 0.2.2.1 has requirement numpy>=1.17.3, but you'll have numpy 1.16.4 which is incompatible.
ERROR: google-cloud-bigquery 1.24.0 has requirement google-auth<2.0dev,>=1.9.0, but you'll have google-auth 1.6.3 which is incompatible.
ERROR: jupyterlab 1.2.6 has requirement tornado!=6.0.0,!=6.0.1,!=6.0.2, but you'll have tornad
```

Maybe I just was ignoring/not noticing it before. But things seem to run.

**Comment by jlewi** [comment]
@hamelsmu this is ready for review

**Pull request merged**
