### PR TITLE
Support triaging multiple repositories

### PR DESCRIPTION
**Pull request by jlewi**
* We want to expand our triage process to multiple repositories and not just
  the kubeflow/kubeflow repository

* This PR updates the notebook to easily processing multiple repositories
  to determine which issues need triage and adding them to the appropriate
  Kanban board.

* Related to kubeflow/community#306

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/68)

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jlewi Actions also has a cron system where we can run periodic jobs that are not tied to any event.  Do you want to run this kind of thing in that?

**Comment by jlewi** [comment]
@hamelsmu  That's good to know. The cron functionality will be useful but I don't have an immediate need for this notebook now that we have the GitHub action updating each issue after its run.

I think cron will be useful for doing a level based design; e.g. in addition to running things on postsubmit we'd like to trigger them at regular intervals. For example, building the docker image for the github action. This way we automatically recover in the event a post-submit run fails because of some temporary issue.

**Comment by jlewi** [comment]
Not sure why there are conflict markers. I'm going to try opening on a new PR.

**Comment by jlewi** [comment]
/assign @abhi-g 

@abhi-g could you take a look please.

**Pull request merged**
