### PR TITLE
Collect stats about issues to triage.

### PR DESCRIPTION
**Pull request by jlewi**
* Use variables with the query to fetch issues
* Add a new download function to download issues
* Write issues to files using multi-line pretty printed json; write the items
  as an array of items.

* To compute stats we need to fetch information about the times at which
  various events occurred so we can determine when an issue was triaged.

* We can then plot the number of untriaged issues as a function of time.

Related to kubeflow/community#280

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/32)

### CODE REVIEW

**Comment by jlewi** [comment]
@abcdefgs0324 @hamelsmu ping; could one of you take a look at this please.

**Comment by hamelsmu** [comment]
Wow I never got the first ping .... it was buried in many other notifications.  I don't know how you deal with this as a maintainer

**Comment by hamelsmu** [comment]
@jlewi can you annotate the notebook a bit more with some prose?

**Comment by jlewi** [comment]
@hamelsmu I think I answered your first 2 questions;

For your last 

> A preview of some of the data you are pulling or some descriptive statistics that give some color of what the data is

I wasn't quite sure what data and statistics to illustrate. The raw data is GitHub issues. We then preprocess this to compute a pandas dataframe with data about when it was opened and when it was triaged (if it was triaged).

Any suggestions?

**Comment by hamelsmu** [comment]
@jlewi its not necessary anymore, there is enough context from the rest of the updated markdown that I understand what is going on now.  

One nit is that you have INFO level logging spamming the notebook, otherwise:
/lgtm

I guess you could use this graph on how Issue Label Bot helped start to gain control over issues?

image

**Comment by hamelsmu** [comment]
@jlewi one more nit, it might be useful if you include the business logic of what counts as triage in the notebook from https://github.com/kubeflow/community/issues/280

Just copy and paste the below from that issue
```
Here's my initial proposal

The following needs to be true for an issue to be considered triaged

It has one the labels ("bug", "question", "enhancement")
It has a priority
If its P0/P1 it should be added to a kanban board
It has at least one "area" label
I will create a simple script that iterates over our issues and does the following

Adds untriaged issues to a project used for triaging issues

I think a project is better than a label because we can potentially use cards to keep track of an issue; e.g. if there is some question about an issue and it needs to be discussed at the community meeting
Add a comment on the issue explaining what criterion are missing for the issue to be considered triaged
```

**Pull request merged**
