### PR TITLE
Fetch GitHub issues and associated comments using GraphQL

### PR DESCRIPTION
**Pull request by jlewi**
* We use GraphQL because we want to fetch the issue body and the comments
  and this is easier with GraphQL then with rest

* Dump the data to files.

* Also Add code to write notifications to a file.

* Fix bug with Fire; methods were missing self argument.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/15)

### CODE REVIEW

**Comment by hamelsmu** [comment]
Some concerns for discussion:

- I’m not sure the API is the best way to gather data in bulk bc of rate limiting.  For example can you obtain all issues from kubernetes/kubernetes this way?

- You may want to authenticate as an app, rather than a user as these are different and will cause you lots of pain refactoring this later.  Here is some info but you can also see our blog post https://developer.github.com/apps/differences-between-apps/

**Comment by hamelsmu** [comment]
We also may want to develop a common way to fetch data across the projects and perhaps make that into a python library questions to consider:

- Fetching isssues in Bulk
- Fetching notifications in Bulk
- Way to store json payloads received from subscribing to GitHub Events 
- etc

Thoughts?

**Comment by hamelsmu** [comment]
FYI typing from my phone so wrote comments incrementally by editing them.  Sorry for the noise, but if you read these comments through email please check the GitHub issue instead.  Thanks

**Comment by jlewi** [comment]
* re Using a GitHub APP; that's a really good idea and one I hadn't thought about

   * IUUC looking at the sample [code](https://github.com/kubeflow/code-intelligence/blob/5b3fd9ce5975237651494e7fb81e4f9c5635b785/Issue-Label-Bot-v1/flask_app/mlapp.py#L83) to authenticate as a GitHub app we just need to generate a JWT and then attach it in the request header. So I think we can refactor the code to support that in the future without much trouble

* Regarding API limits

   * It looks like kubernetes/kubernetes has ~30K issues
   * vscode ~70K
   * It looks like the API limits are 5000 / hour 
   * Right now we fetch 100 issues per request
   * So we should be able to pull ~500K issues per hour
   * We probably want to have separate apps for serving and training so that onboarding new repositories doesn't cause us to run out of quota for labeling issues
  
* Overtime we can do more sophisticated things like not pull the issues all at once

   * e.g. we could break issues into chunks of N days and then enqueue jobs to pull each chunk
   * We might want to do this to support retraining; i.e. we could continually cycle through all our repos and for each repo pull the issues that have been updated since time T.
   * We would want to treat T as a watermark and continually advance it trying to keep it updated as much  as possible
 
* Listening for GitHub events to issues might cut down on events but

   * I'm not sure if this would contain all of the data we need (e.g. the full title, body, labels, comment stream)
   * If we listen for the deltas and then try to reconstruct the issue from the deltas; the design might be more brittle
          * i.e. it could be more difficult to ensure we don't miss events
    * A design which automatically recovers is easier to operate
          * e.g. imagine our system goes down for N hours; if we we're listening for github events then we need some way to backfill for those hours we were down
          * However if we persist a watermark that indicates we have downloaded updates to time T, then we can just resume pulling updates after time T. 
          * It might take some time based on rate throttling but eventually the system should recover and we should have a copy of all issues

**Pull request merged**
