### PR TITLE
moved files for better organization

### PR DESCRIPTION
**Pull request by hamelsmu**
Closes https://github.com/kubeflow/code-intelligence/issues/36

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/code-intelligence/37)

### CODE REVIEW

**Comment by abcdefgs0324** [comment]
Should we rename `py/code_intelligence` to be something like `py/issue_triage` in order to separate the subdirectories in `py/` ?

**Comment by hamelsmu** [comment]
> Should we rename `py/code_intelligence` to be something like `py/issue_triage` in order to separate the subdirectories in `py/` ?

Absolutely, I re-arranged this in a way that makes sense (I think)

**Comment by jlewi** [comment]
Why not have a structure like

```
py/code_intelligence/${PROJECT}/...
py/code_intelligence/util
```

This way we can keep code_intelligence as a top level package and have sub packages for different projects as well as code shared across projects.

**Comment by hamelsmu** [comment]
Yeah that’s what this PR does

**Comment by jlewi** [comment]
Thanks @hamelsmu 

It looks like this PR is creating packages code_intelligence.triage and code_intelligence.notifications

That part looks good to me.

It also looks like it is renaming the notebook
File renamed from py/code_intelligence/triage.ipynb to Issue-Triage/notebooks/triage.ipynb 

Why organize notebooks in Issue-Triage? Should we just have a single top-level directory for noebooks?

e.g.

py/code_intelligence/....
notebooks/triage.ipynb
notebooks/....

If we want to have multiple notebooks corresponding to projects should we do it as

notebooks/${PROJECT}/...

**Comment by hamelsmu** [comment]
👋 Hi @jlewi, let me try to respond to this question: 

> Why organize notebooks in Issue-Triage? Should we just have a single top-level directory for noebooks?

My motivation for moving the notebooks into an application-specific folder is notebooks are the following:

- Obstensively, you might have separate dependencies per project/Micro-service.  
- I proposed moving the notebook with the intent of separate requirements.txt and Pipfile per micro service for easier dependency management (this is up for debate though in an upcoming meeting). 
- I was categorizing notebooks as being more part of a microservice than as part of common modules used across projects.  

I made some comments [here](https://github.com/kubeflow/code-intelligence/pull/34#issuecomment-520436162) discussing some of my thinking (which I'm open to changing if there are suggestions).

**Comment by hamelsmu** [comment]
@jlewi @abcdefgs0324 

I updated this PR to make the changes we discussed.  The new directory structure is as follows:

```
├── Issue_Embeddings
│   ├── deployment
│   ├── flask_app
│   ├── hyperparam_sweep
│   ├── notebooks
│   └──script
├── Issue_Triage
│   ├── notebooks
│   └── tests
├── Label_Microservice
│   ├── notebooks
│   └── tests
├── Notifications
│   └── tests
└── py
    ├── code_intelligence/
    ├── issue_triage/
    └── notifications/

```

Additionally, in each application {Label_Microservice, Issue_Triage, Issue_Embeddings} the goal is to have the following files and directories:

- `scripts/` to bootstrap the environment and run the tests
- `notebooks/` that run the environment
- `requirements.txt` and `Pipfile.lock` for dependencies
- `deploy/` with yaml files for kubeflow deployments
etc. 

@jlewi @abcdefgs0324 let me know if you approve.  This PR is large b/c when you change directory names it touches all the children as well

**Pull request merged**
