### PR TITLE
Update 01_AcquireData.ipynb

### PR DESCRIPTION
**Pull request by GauravSarkar**
The dataframes are stored as HDF5 files instead of pickle files as per requirements. Please kindly check and merge.This is regarging 
issue #123 .

### CODE REVIEW

**Comment by GauravSarkar** [comment]
@googlebot I signed it!

**Comment by jlewi** [comment]
Please combine all the PRs for switching to HDF5 into one PR. This way it is possible to review whether all the code is changed consistently to use HDF5 instead of pickle

**Comment by GauravSarkar** [comment]
okay I will combine all the changes in a single PR.

**Comment by GauravSarkar** [comment]
I have made changes to all the notebooks by commiting in the PR Update 02_fastai_DataBunch.ipynb

**Comment by jlewi** [comment]
Closing this PR; Unfortunately this repo isn't really being maintained anymore.

**Pull request closed without merging**
